[book]
authors = ["Chevdor", "PierreBesson", "SBalaguer"]
language = "en"
multilingual = false
src = "src"
title = "Polkadot Network Directory"

# [book]
# title = "Polkadot Network Directory"
# description = "A directory of the relay and parachains of the polkadot network"
# authors = ["chevdor"]
# language = "en"

# [rust]
# edition = "2018"

[output.html]
site-url = "/polkadot_network_directory/"
git-repository-url = "https://github.com/paritytech/polkadot_network_directory"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/paritytech/polkadot_network_directory/edit/master/{path}"
