[book]
authors = ["Chevdor", "PierreBesson", "SBalaguer"]
language = "en"
multilingual = false
src = "src"
title = "Polkadot Network Directory"

# [book]
# title = "Polkadot Network Directory"
# description = "A directory of the relay and parachains of the polkadot network"
# authors = ["chevdor"]
# language = "en"

# [rust]
# edition = "2018"

# [output.html]
# mathjax-support = true

# [output.html.playground]
# editable = true
# line-numbers = true

# [output.html.search]
# limit-results = 20
# use-boolean-and = true
# boost-title = 2
# boost-hierarchy = 2
# boost-paragraph = 1
# expand = true
# heading-split-level = 2

# [output.html.redirect]
# "/format/config.html" = "configuration/index.html"
